# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Going'), (2, 'Maybe'), (3, 'Unknown'), (4, 'Not going')], default=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_calendar.Event')),
            ],
        ),
        migrations.CreateModel(
            name='GuestChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('timezone', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_calendar.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='MyCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mycalendar',
            name='can_modify',
            field=models.ManyToManyField(related_name='calendars_to_modify', to='my_calendar.UserProfile'),
        ),
        migrations.AddField(
            model_name='mycalendar',
            name='can_read',
            field=models.ManyToManyField(related_name='calendars_to_read', to='my_calendar.UserProfile'),
        ),
        migrations.AddField(
            model_name='mycalendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_calendars', to='my_calendar.UserProfile'),
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_calendar.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_calendar.MyCalendar'),
        ),
    ]
