# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0002_auto_20160824_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomsettings',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
