# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0007_auto_20160919_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='can_read',
            field=models.ManyToManyField(blank=True, related_name='calendars_to_read', to='my_calendar.UserProfile'),
        ),
    ]
