# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0008_auto_20160922_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='can_modify',
            field=models.ManyToManyField(blank=True, related_name='calendars_to_modify', to='my_calendar.UserProfile'),
        ),
    ]
