# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0009_auto_20160923_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([('event', 'user')]),
        ),
    ]
