# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0011_auto_20161009_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomsettings',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_calendar.Guest'),
        ),
    ]
