# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0012_auto_20161009_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='state',
            new_name='attending_status',
        ),
    ]
