# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0013_auto_20161009_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycalendar',
            old_name='can_modify',
            new_name='modifiers',
        ),
        migrations.RenameField(
            model_name='mycalendar',
            old_name='can_read',
            new_name='readers',
        ),
    ]
