# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import my_calendar.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0018_auto_20180610_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='color',
            field=models.CharField(max_length=7, validators=[my_calendar.models.validate_color]),
        ),
    ]
